version: "3"

services:
  db:
    image: mysql:5
    restart: always
    ports:
      - "3307:3306"
    networks:
      - db
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
networks:
  db:
    external: false
